export default function Head() {
  return (
    <>
      <title>BPM</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" sizes="21x21" href="/logo.svg" />
    </>
  )
}
